// =============================================================================
// AutoSpace Deals — Deal Inventory
// =============================================================================
// This file is the single source of truth for every deal shown on the site.
// It is plain TypeScript data (no database yet), so adding or editing a deal
// is as simple as copying a block below and changing the values.
//
// HOW TO ADD A NEW DEAL:
//   1. Copy any object inside the `deals` array below.
//   2. Give it a new unique `id` and `slug` (slug = URL-friendly name, e.g.
//      "2026-bmw-x5-xdrive40i-ca").
//   3. Fill in the real numbers from the dealer/broker's offer.
//   4. Save the file — the homepage and detail page update automatically.
//
// PHOTOS: We don't have real dealer photos yet, so `images` currently points
// at generic stock photos grouped by body style / fuel type (see the
// STOCK_IMAGES block below) just so the site doesn't look empty or broken.
// Replace the `images` array on any deal with real photo URLs whenever a
// dealer/broker sends real pictures — nothing else needs to change.
// =============================================================================

export type SellerType = "Dealer" | "Broker";
export type DealType = "Lease" | "Finance";
export type FuelType = "Gas" | "Hybrid" | "PHEV" | "EV";
export type BodyStyle =
  | "Sedan"
  | "SUV"
  | "Truck"
  | "Coupe"
  | "Minivan"
  | "Hatchback";

export interface Deal {
  id: number;
  slug: string;

  // Vehicle
  year: number;
  make: string;
  model: string;
  trim: string;
  bodyStyle: BodyStyle;
  fuel: FuelType;
  exterior: string;
  interior: string;

  // Deal
  dealType: DealType;
  msrp: number;
  sellingPrice: number; // negotiated price before tax — used to calc MSRP discount
  payment: number; // monthly payment
  dueAtSigning: number; // due at signing (lease) or down payment (finance)
  term: number; // months
  milesPerYear: number | null; // null for finance deals
  apr: number | null; // annual %, only used for finance deals

  // Seller
  sellerType: SellerType;
  sellerName: string;
  sellerPhone: string;
  sellerEmail: string;
  city: string;
  state: string; // 2-letter code

  // Trust / status
  verified: boolean;
  inStock: boolean;
  popularity: number; // 0-100, used for "Most popular" sort
  datePosted: string; // ISO date (YYYY-MM-DD)

  // Content
  badge?: string;
  notes: string;
  packages: string[];
  images: string[];

  // Provenance — where this listing came from. Optional; used for real deals
  // pulled from a broker's public posts (e.g. their Leasehackr thread) so we
  // can trace it back and re-verify pricing later.
  sourceUrl?: string;

  // Sample/demo listing flag. True for placeholder deals used to fill out
  // the site before we have a full pipeline of real broker/dealer inventory.
  // Sample listings use stock photos that are NOT guaranteed to match the
  // exact year/trim — they're illustrative only, and the UI must badge them
  // clearly so nobody mistakes a sample listing for a real, verified one.
  sample?: boolean;
}

// -----------------------------------------------------------------------------
// Stock category images (see note above). All hosted on Unsplash.
// -----------------------------------------------------------------------------
const STOCK_IMAGES = {
  ev: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1600&q=80",
  sedan:
    "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1600&q=80",
  suv: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1600&q=80",
  hatchback:
    "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=1600&q=80",
  performance:
    "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1600&q=80",
  generic:
    "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1600&q=80",
};

export function stockImageFor(fuel: FuelType, bodyStyle: BodyStyle): string {
  if (fuel === "EV") return STOCK_IMAGES.ev;
  if (bodyStyle === "Coupe") return STOCK_IMAGES.performance;
  if (bodyStyle === "Sedan") return STOCK_IMAGES.sedan;
  if (bodyStyle === "SUV") return STOCK_IMAGES.suv;
  if (bodyStyle === "Hatchback") return STOCK_IMAGES.hatchback;
  return STOCK_IMAGES.generic; // Truck, Minivan, anything else
}

// -----------------------------------------------------------------------------
// Deals
// -----------------------------------------------------------------------------
export const deals: Deal[] = [
  {
    id: 1,
    slug: "2026-bmw-i4-edrive40-ca",
    year: 2026,
    make: "BMW",
    model: "i4 eDrive40",
    trim: "Base",
    bodyStyle: "Sedan",
    fuel: "EV",
    exterior: "Vegas Red",
    interior: "Black",
    dealType: "Lease",
    msrp: 64000,
    sellingPrice: 60200,
    payment: 459,
    dueAtSigning: 3500,
    term: 36,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "test",
    sample: true,
    sellerPhone: "747-555-2210",
    sellerEmail: "deals@socalautobrokers.example",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 92,
    datePosted: "2026-06-29",
    badge: "EV",
    notes:
      "Loyalty required — must currently own or lease a BMW. Based on a 7.75% base money factor before any credit adjustments. Price and incentives can change at any time.",
    packages: ["Premium Package", "Parking Assistant", "Driving Assistance Pro", "Shadowline Trim"],
    images: ["https://di-uploads-pod32.dealerinspire.com/caseybmw/uploads/2025/12/2026-BMW-i4-eDrive40-Red.png"],
  },
  {
    id: 2,
    slug: "2026-bmw-x5-xdrive40i-ca",
    year: 2026,
    make: "BMW",
    model: "X5",
    trim: "xDrive40i",
    bodyStyle: "SUV",
    fuel: "Gas",
    exterior: "Alpine White",
    interior: "Cognac",
    dealType: "Lease",
    msrp: 71200,
    sellingPrice: 66800,
    payment: 689,
    dueAtSigning: 4500,
    term: 36,
    milesPerYear: 10000,
    apr: null,
    sellerType: "Broker",
    sellerName: "test",
    sample: true,
    sellerPhone: "747-555-2210",
    sellerEmail: "deals@socalautobrokers.example",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 78,
    datePosted: "2026-06-25",
    badge: "HOT",
    notes: "No loyalty required. Tax, title, and registration are additional and vary by county.",
    packages: ["Premium Package", "20\" Wheels", "Convenience Package"],
    images: [
      "https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/o10qiMPxXkopc2mFsQ0AUs_xru79YZFSeXSVQkY2w4NlDrU74XvajDCTMdJdgADwu8ZxJ1V9jM9pLkbxlEmd87kbSW8dwQrxPGh0u6WUmmPUxsfCq8rOsjY5MpXvoDz-oyq3PNUY0JXrZ6rskxqYLKK5rMO78JvZ7k479i9czmeUrD5zP8tEVMCUissbJrxRllHzTg7fgiE/cc_2026BMS191998056_01_640_300.png",
    ],
  },
  {
    id: 3,
    slug: "2026-audi-q5-premium-plus-ca",
    year: 2026,
    make: "Audi",
    model: "Q5",
    trim: "Premium Plus",
    bodyStyle: "SUV",
    fuel: "Gas",
    exterior: "Glacier White",
    interior: "Black",
    dealType: "Lease",
    msrp: 58240,
    sellingPrice: 55100,
    payment: 589,
    dueAtSigning: 3500,
    term: 36,
    milesPerYear: 10000,
    apr: null,
    sellerType: "Dealer",
    sellerName: "test",
    sample: true,
    sellerPhone: "415-555-2244",
    sellerEmail: "leasing@bayareaaudi.example",
    city: "San Jose",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 64,
    datePosted: "2026-06-30",
    badge: "HOT",
    notes: "Loyalty or conquest incentive already applied to the advertised payment. Subject to credit approval.",
    packages: ["Premium Plus", "Navigation Package"],
    images: ["https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/Opm-o5Il9qxgIojKpnMfz_V4AJwRpp8jWNS9lyki2OE1PB7HXUwkM8DRlDfZc49E5gL5zeipcXxss4lCvyeh3EgPIgcFyqQgDG5oWyXSfW814eV5ZNEKrzOL5wZ_L5ps_Q4x8LWlAkRPB_pdXFAiUdpKMAgOGEUHJL6M-_jigj3ho0-WHg4NY9jh0ukiVgeX/cc_2026AUS022035134_01_640_Z9Z9.png"],
  },
  {
    id: 4,
    slug: "2025-tesla-model-3-long-range-ny",
    year: 2025,
    make: "Tesla",
    model: "Model 3",
    trim: "Long Range",
    bodyStyle: "Sedan",
    fuel: "EV",
    exterior: "Gray Metallic",
    interior: "White",
    dealType: "Lease",
    msrp: 52990,
    sellingPrice: 49500,
    payment: 499,
    dueAtSigning: 2500,
    term: 36,
    milesPerYear: 12000,
    apr: null,
    sellerType: "Broker",
    sellerName: "test",
    sample: true,
    sellerPhone: "212-555-0133",
    sellerEmail: "hello@evleasepros.example",
    city: "New York",
    state: "NY",
    verified: true,
    inStock: true,
    popularity: 71,
    datePosted: "2026-06-20",
    badge: "EV",
    notes: "Includes federal and state EV lease credit passed through by the lender. Confirm current eligibility before signing.",
    packages: ["Long Range Battery", "Autopilot"],
    images: ["https://autoimage.capitalone.com/stock-media/chrome/2025-Tesla-Model_3-Long_Range-PN01-cc_2025TSC031930472_01_2100_PN01.png"],
  },
  {
    id: 5,
    slug: "2026-tesla-model-y-long-range-ny",
    year: 2026,
    make: "Tesla",
    model: "Model Y",
    trim: "Long Range",
    bodyStyle: "SUV",
    fuel: "EV",
    exterior: "Pearl White",
    interior: "Black",
    dealType: "Finance",
    msrp: 54990,
    sellingPrice: 52200,
    payment: 719,
    dueAtSigning: 4000,
    term: 60,
    milesPerYear: null,
    apr: 5.4,
    sellerType: "Dealer",
    sellerName: "test",
    sample: true,
    sellerPhone: "212-555-0177",
    sellerEmail: "sales@manhattanevgallery.example",
    city: "New York",
    state: "NY",
    verified: false,
    inStock: true,
    popularity: 58,
    datePosted: "2026-06-15",
    badge: "NEW",
    notes: "Finance offer, not a lease. APR based on tier-1 credit approval; actual rate depends on final credit approval.",
    packages: ["Long Range Battery", "Enhanced Autopilot"],
    images: ["https://autoimage.capitalone.com/stock-media/chrome/2026-Tesla-Model_Y-Long_Range_Launch_Series-PPSW-cc_2026TSS021956392_01_2100_PPSW.png"],
  },
  {
    id: 6,
    slug: "2025-honda-cr-v-hybrid-sport-touring-nj",
    year: 2025,
    make: "Honda",
    model: "CR-V Hybrid",
    trim: "Sport Touring",
    bodyStyle: "SUV",
    fuel: "Hybrid",
    exterior: "Canyon River Blue",
    interior: "Black",
    dealType: "Lease",
    msrp: 41250,
    sellingPrice: 39400,
    payment: 429,
    dueAtSigning: 2999,
    term: 39,
    milesPerYear: 10000,
    apr: null,
    sellerType: "Dealer",
    sellerName: "test",
    sample: true,
    sellerPhone: "973-555-6612",
    sellerEmail: "internet@gardenstatehonda.example",
    city: "Newark",
    state: "NJ",
    verified: true,
    inStock: true,
    popularity: 66,
    datePosted: "2026-06-27",
    badge: "VALUE",
    notes: "Tax not included in advertised payment. Sale price reflects all available manufacturer incentives.",
    packages: ["Touring Package"],
    images: ["https://file.kelleybluebookimages.com/kbb/base/evox/CP/54861/2025-Honda-CR-V%20Hybrid-front_54861_032_1853x855_WX_cropped.png"],
  },
  {
    id: 7,
    slug: "2025-honda-civic-hatchback-sport-nj",
    year: 2025,
    make: "Honda",
    model: "Civic",
    trim: "Sport Hatchback",
    bodyStyle: "Hatchback",
    fuel: "Gas",
    exterior: "Rallye Red",
    interior: "Black",
    dealType: "Finance",
    msrp: 27650,
    sellingPrice: 25900,
    payment: 349,
    dueAtSigning: 1999,
    term: 60,
    milesPerYear: null,
    apr: 4.9,
    sellerType: "Dealer",
    sellerName: "test",
    sample: true,
    sellerPhone: "973-555-6612",
    sellerEmail: "internet@gardenstatehonda.example",
    city: "Newark",
    state: "NJ",
    verified: true,
    inStock: true,
    popularity: 41,
    datePosted: "2026-06-18",
    badge: "VALUE",
    notes: "Finance offer requires tier-1 credit approval. Price reflects dealer discount before tax, title, and fees.",
    packages: ["Sport Trim", "Alloy Wheels"],
    images: ["https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-hatchback/AW/Carshot/carshot_CivicHatchback_front_CIVIC20LHATCHSPORT_2025_RallyeRed_FL2H8SEW_R-513.png"],
  },
  {
    id: 8,
    slug: "2025-porsche-macan-base-fl",
    year: 2025,
    make: "Porsche",
    model: "Macan",
    trim: "Base",
    bodyStyle: "SUV",
    fuel: "Gas",
    exterior: "Jet Black",
    interior: "Bordeaux Red",
    dealType: "Lease",
    msrp: 68400,
    sellingPrice: 64900,
    payment: 899,
    dueAtSigning: 7000,
    term: 36,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "test",
    sample: true,
    sellerPhone: "305-555-4471",
    sellerEmail: "concierge@sunshineexotic.example",
    city: "Miami",
    state: "FL",
    verified: true,
    inStock: true,
    popularity: 55,
    datePosted: "2026-06-22",
    badge: "NEW",
    notes: "Demo unit with under 2,000 miles. Full factory warranty applies.",
    packages: ["Sport Chrono Package"],
    images: ["https://platform.cstatic-images.com/in/v2/stock_photos/8107907e-3b88-43e8-ab23-5dfbecad4124/ffeb4d15-6d70-4e97-b1d3-5f7b8b8e0cfe.png"],
  },
  {
    id: 9,
    slug: "2024-porsche-911-carrera-fl",
    year: 2024,
    make: "Porsche",
    model: "911",
    trim: "Carrera",
    bodyStyle: "Coupe",
    fuel: "Gas",
    exterior: "Guards Red",
    interior: "Black",
    dealType: "Lease",
    msrp: 118000,
    sellingPrice: 112500,
    payment: 1650,
    dueAtSigning: 9500,
    term: 36,
    milesPerYear: 5000,
    apr: null,
    sellerType: "Broker",
    sellerName: "test",
    sample: true,
    sellerPhone: "305-555-4471",
    sellerEmail: "concierge@sunshineexotic.example",
    city: "Miami",
    state: "FL",
    verified: true,
    inStock: false,
    popularity: 88,
    datePosted: "2026-06-10",
    badge: "HOT",
    notes: "This unit is currently pending sale. Broker can source a similar allocation — contact for availability.",
    packages: ["Sport Chrono Package", "PASM Sport Suspension"],
    images: ["https://file.kelleybluebookimages.com/kbb/base/evox/CP/50643/2024-Porsche-911-front_50643_032_2400x1800_G1_nologo.png"],
  },
  {
    id: 10,
    slug: "2026-toyota-rav4-hybrid-xle-tx",
    year: 2026,
    make: "Toyota",
    model: "RAV4",
    trim: "Hybrid XLE",
    bodyStyle: "SUV",
    fuel: "Hybrid",
    exterior: "Magnetic Gray",
    interior: "Black",
    dealType: "Lease",
    msrp: 36800,
    sellingPrice: 35200,
    payment: 389,
    dueAtSigning: 2500,
    term: 36,
    milesPerYear: 12000,
    apr: null,
    sellerType: "Dealer",
    sellerName: "test",
    sample: true,
    sellerPhone: "512-555-7788",
    sellerEmail: "sales@lonestartoyota.example",
    city: "Austin",
    state: "TX",
    verified: true,
    inStock: true,
    popularity: 74,
    datePosted: "2026-07-01",
    badge: "VALUE",
    notes: "Regional Toyota lease support included in advertised payment. Confirm current APR/lease rates with dealer.",
    packages: ["XLE Convenience Package"],
    images: ["https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/LMd-9QmYj0TIKmjuiGTIVIAyPpWGgUaas9UkIwUHDfunO6Zuq4BFCQPIwp0L4n6KlxDaJG-pOCwoCNpfs9kZy8IfPwsr5wbYAfVYGF8TSzIBBjEkVoWlTj_yyLxMVWPw2L9dY9HDJrNIjYRwsW4aQ8z9t7hjbWgl1QFYd2gMbqsHDMcj54Ttlw/cc_2026TOS112033667_01_640_218.png"],
  },
  {
    id: 11,
    slug: "2025-ford-f-150-lariat-tx",
    year: 2025,
    make: "Ford",
    model: "F-150",
    trim: "Lariat",
    bodyStyle: "Truck",
    fuel: "Gas",
    exterior: "Oxford White",
    interior: "Black",
    dealType: "Finance",
    msrp: 58900,
    sellingPrice: 54500,
    payment: 749,
    dueAtSigning: 3000,
    term: 72,
    milesPerYear: null,
    apr: 5.9,
    sellerType: "Dealer",
    sellerName: "test",
    sample: true,
    sellerPhone: "512-555-9021",
    sellerEmail: "trucks@lonestarford.example",
    city: "Austin",
    state: "TX",
    verified: false,
    inStock: true,
    popularity: 47,
    datePosted: "2026-06-12",
    badge: "NEW",
    notes: "Price includes Ford truck month incentive. APR shown is the best-case tier-1 rate.",
    packages: ["Lariat Sport Package", "Tow Package"],
    images: ["https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/LEaf6etXBo1PrtbQydb8M4uLiR8MTAiArmq5aWM6ggdx1uPGX-I0aFA9qpiHGLP9YK9obGPY6pH2bObXVHBqXWQQEPYO9yr-rE-joos7tH_5MAcNF4YJmQZbS0sHHqTWM5-_hZOovfamgywLTMQAglrx46B1K2zHQLrmHrLb26Z07-7Pwfwf_6KVjyvDEWcj7ZVMB5IeaBE/cc_2025FOT112016063_01_640_A3.png"],
  },
  {
    id: 12,
    slug: "2026-jeep-grand-cherokee-limited-il",
    year: 2026,
    make: "Jeep",
    model: "Grand Cherokee",
    trim: "Limited",
    bodyStyle: "SUV",
    fuel: "Gas",
    exterior: "Diamond Black",
    interior: "Black",
    dealType: "Lease",
    msrp: 47500,
    sellingPrice: 44800,
    payment: 459,
    dueAtSigning: 2999,
    term: 36,
    milesPerYear: 10000,
    apr: null,
    sellerType: "Dealer",
    sellerName: "test",
    sample: true,
    sellerPhone: "312-555-3345",
    sellerEmail: "leasing@windycityjeep.example",
    city: "Chicago",
    state: "IL",
    verified: true,
    inStock: true,
    popularity: 52,
    datePosted: "2026-06-24",
    badge: "VALUE",
    notes: "Loyalty incentive applied. Tax, title, license, and doc fees are additional.",
    packages: ["Limited Package", "Panoramic Sunroof"],
    images: ["https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/It38wX8WXQivo8iiX3aiflXq9atjDWsn3APYdZ4f_iGOCrUxyoD31Kz-s2KT2OoGQRR204UbKN5zuWSCQ1OPaYh_OY9gdQuBfkQiLrk1dDmC0ds9oehDtodndNCmXqUnYMHKrmXknPO0ZcrdbyPg17lyK9a8SlMBDbuLFLhWwnGGYLJAKOCObg/cc_2026JES052064422_01_640_PXJ.png"],
  },
  {
    id: 13,
    slug: "2025-hyundai-ioniq-5-sel-il",
    year: 2025,
    make: "Hyundai",
    model: "Ioniq 5",
    trim: "SEL",
    bodyStyle: "SUV",
    fuel: "EV",
    exterior: "Cyber Gray",
    interior: "Black",
    dealType: "Lease",
    msrp: 46800,
    sellingPrice: 43900,
    payment: 349,
    dueAtSigning: 2999,
    term: 36,
    milesPerYear: 10000,
    apr: null,
    sellerType: "Broker",
    sellerName: "test",
    sample: true,
    sellerPhone: "312-555-7710",
    sellerEmail: "deals@midwestevbrokers.example",
    city: "Chicago",
    state: "IL",
    verified: true,
    inStock: true,
    popularity: 69,
    datePosted: "2026-06-28",
    badge: "EV",
    notes: "Federal EV lease incentive passed through in advertised payment. Broker fee applies at signing.",
    packages: ["SEL Convenience Package"],
    images: ["https://vehicle-images.carscommerce.inc/89d7-11000259/7YAKNDDC1SY004691/1d8dd5f97abba655c23c72ab805f62bf.png"],
  },
  {
    id: 14,
    slug: "2026-kia-telluride-sx-il",
    year: 2026,
    make: "Kia",
    model: "Telluride",
    trim: "SX",
    bodyStyle: "SUV",
    fuel: "Gas",
    exterior: "Wolf Gray",
    interior: "Black",
    dealType: "Lease",
    msrp: 52400,
    sellingPrice: 49800,
    payment: 559,
    dueAtSigning: 3500,
    term: 36,
    milesPerYear: 10000,
    apr: null,
    sellerType: "Dealer",
    sellerName: "test",
    sample: true,
    sellerPhone: "312-555-9987",
    sellerEmail: "sales@windycitykia.example",
    city: "Chicago",
    state: "IL",
    verified: false,
    inStock: true,
    popularity: 38,
    datePosted: "2026-06-08",
    badge: "NEW",
    notes: "3-row SUV, current model year. Advertised payment assumes tier-1 credit through Kia Finance.",
    packages: ["SX Prestige Package", "3rd Row Seating"],
    images: ["https://di-uploads-pod36.dealerinspire.com/qualitykiaofgreenwood/uploads/2025/02/2025-Kia-Telluride-Glacial-White-Pearl-Quality-Kia-of-Greenwood-SC.png"],
  },
  {
    id: 15,
    slug: "2025-chrysler-pacifica-limited-nj",
    year: 2025,
    make: "Chrysler",
    model: "Pacifica",
    trim: "Limited",
    bodyStyle: "Minivan",
    fuel: "Gas",
    exterior: "Velvet Red",
    interior: "Black",
    dealType: "Lease",
    msrp: 49900,
    sellingPrice: 46200,
    payment: 469,
    dueAtSigning: 2999,
    term: 36,
    milesPerYear: 10000,
    apr: null,
    sellerType: "Dealer",
    sellerName: "test",
    sample: true,
    sellerPhone: "973-555-2201",
    sellerEmail: "internet@gardenstatechrysler.example",
    city: "Elizabeth",
    state: "NJ",
    verified: true,
    inStock: true,
    popularity: 33,
    datePosted: "2026-06-05",
    badge: "VALUE",
    notes: "Stow 'n Go seating. Advertised payment includes current manufacturer lease cash.",
    packages: ["Limited Package", "Stow 'n Go Seating", "Rear Entertainment"],
    images: ["https://autoimage.capitalone.com/stock-media/evox/2025-Chrysler-Pacifica-Select-PR6-55842_cc2400_032_PR6.png"],
  },
  {
    id: 16,
    slug: "2026-mazda-cx-5-premium-ca",
    year: 2026,
    make: "Mazda",
    model: "CX-5",
    trim: "Premium",
    bodyStyle: "SUV",
    fuel: "Gas",
    exterior: "Machine Gray",
    interior: "Black",
    dealType: "Lease",
    msrp: 35400,
    sellingPrice: 33600,
    payment: 359,
    dueAtSigning: 2500,
    term: 36,
    milesPerYear: 10000,
    apr: null,
    sellerType: "Broker",
    sellerName: "test",
    sample: true,
    sellerPhone: "747-555-2210",
    sellerEmail: "deals@socalautobrokers.example",
    city: "Los Angeles",
    state: "CA",
    verified: false,
    inStock: true,
    popularity: 29,
    datePosted: "2026-06-14",
    badge: "VALUE",
    notes: "Broker fee of $599 applies at signing, included in the due-at-signing figure shown.",
    packages: ["Premium Package", "Bose Audio"],
    images: ["https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/A6ZVqgdvNgOiQq-_wJpkX_qpj--IgVkudnCgIYuqRt6JxmDFlOmjPYq4DtjyAJkaswTgZgxrVkNz_jB04K1tYtchCAyYDoARXr0ELeY6JuPdQimzEovaegBoy1dLfTlsAzVk03FgCTKKj0DVzb74SwCXwHGOuifDlHMPexGa4I_gpiyTkB8c2I9nEYtckh09/cc_2026MAS062057357_01_640_47C.png"],
  },

  // ---------------------------------------------------------------------
  // Real deals below — sourced from Chrome Stallions' own public posts on
  // their Leasehackr marketplace thread. Chrome Stallions has given
  // permission to be listed on AutoSpace Deals. Prices reflect what the
  // broker posted; confirm current availability before publishing updates,
  // since brokers rotate these specials frequently (these were posted as
  // "May Specials" — reconfirm for the current month before launch).
  // ---------------------------------------------------------------------
  {
    id: 17,
    slug: "2026-mercedes-benz-glc-300-4matic-ca",
    year: 2026,
    make: "Mercedes-Benz",
    model: "GLC 300",
    trim: "4MATIC",
    bodyStyle: "SUV",
    fuel: "Gas",
    exterior: "Polar White",
    interior: "Black",
    dealType: "Lease",
    msrp: 57000, // estimated — Chrome Stallions posts selling price, not full MSRP; confirm sticker with broker
    sellingPrice: 53000,
    payment: 299,
    dueAtSigning: 3500,
    term: 24,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "Chrome Stallions",
    sellerPhone: "949-763-5609",
    sellerEmail: "sales@chromestallions.com",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 80,
    datePosted: "2026-07-04",
    badge: "HOT",
    notes:
      "Payment is +tax. Requires Conquest — an eligible 2020+ vehicle currently registered to you or someone in your household (proof of registration required). $599 broker fee is included in the due-at-signing total above. Serves both Norcal and Socal.",
    packages: ["AMG Line Lite Plus"],
    images: ["/cars/2026-mercedes-glc300-polar-white.png"],
    sourceUrl:
      "https://forum.leasehackr.com/t/chrome-stallions-benz-porsche-exotics-glb-179-3-5k-glc-279-3-5k-911-4s-1499-5k/759811",
  },
  {
    id: 18,
    slug: "2026-mercedes-benz-c300-ca",
    year: 2026,
    make: "Mercedes-Benz",
    model: "C300",
    trim: "Base",
    bodyStyle: "Sedan",
    fuel: "Gas",
    exterior: "Black",
    interior: "Beige",
    dealType: "Lease",
    msrp: 55500, // estimated — see note on GLC 300 above
    sellingPrice: 52000,
    payment: 379,
    dueAtSigning: 3500,
    term: 24,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "Chrome Stallions",
    sellerPhone: "949-763-5609",
    sellerEmail: "sales@chromestallions.com",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 62,
    datePosted: "2026-07-04",
    badge: "VALUE",
    notes:
      "Payment is +tax. Requires Conquest — an eligible 2020+ vehicle currently registered to you or someone in your household (proof of registration required). $599 broker fee is included in the due-at-signing total above.",
    packages: ["Heated & Ventilated Seats", "19\" AMG Multispokes"],
    images: ["https://vehicle-images.carscommerce.inc/stock-images/chrome/3a20930987c9467048d312873b7913e5.png"],
    sourceUrl:
      "https://forum.leasehackr.com/t/chrome-stallions-benz-porsche-exotics-glb-179-3-5k-glc-279-3-5k-911-4s-1499-5k/759811",
  },
  {
    id: 19,
    slug: "2026-mercedes-benz-gle-450-coupe-ca",
    year: 2026,
    make: "Mercedes-Benz",
    model: "GLE 450 Coupe",
    trim: "Base",
    bodyStyle: "SUV",
    fuel: "Gas",
    exterior: "Graphite Gray",
    interior: "Black",
    dealType: "Lease",
    msrp: 86500, // estimated — see note on GLC 300 above
    sellingPrice: 81000,
    payment: 729,
    dueAtSigning: 3500,
    term: 24,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "Chrome Stallions",
    sellerPhone: "949-763-5609",
    sellerEmail: "sales@chromestallions.com",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 57,
    datePosted: "2026-07-04",
    badge: "NEW",
    notes:
      "Coupe-styled SUV. Payment is +tax. Requires Conquest — an eligible 2020+ vehicle currently registered to you or someone in your household (proof of registration required). $699 broker fee is included in the due-at-signing total above.",
    packages: ["Night Package", "Exclusive Trim"],
    images: ["https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/A6ZVqgdvNgNS-tOdpleojQHoHqEV8nKHGlrR76ELO5XWtalKRnDL8BGHYut49a8CXEjwjGd_0bCnS3pA250bC5Ka5L8cIEayqQKh2BXLkRaF8_AqZlrL2kN2Xbx4u8s7I_b0sQ0ufjiaaQWPB2Vc7Hx-xz3FRAa249F-SycEZNiyodpt0DDRTn4MrQsCBsjsQOnu7vItCuU/cc_2026MBSA11972885_02_640_956.png"],
    sourceUrl:
      "https://forum.leasehackr.com/t/chrome-stallions-benz-porsche-exotics-glb-179-3-5k-glc-279-3-5k-911-4s-1499-5k/759811",
  },
  {
    id: 20,
    slug: "2025-porsche-macan-loaner-ca",
    year: 2025,
    make: "Porsche",
    model: "Macan",
    trim: "Base (Loaner)",
    bodyStyle: "SUV",
    fuel: "Gas",
    exterior: "White",
    interior: "Black",
    dealType: "Lease",
    msrp: 66000, // estimated — see note on GLC 300 above
    sellingPrice: 62000,
    payment: 699,
    dueAtSigning: 4995,
    term: 24,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "Chrome Stallions",
    sellerPhone: "949-763-5609",
    sellerEmail: "sales@chromestallions.com",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 48,
    datePosted: "2026-07-04",
    badge: "VALUE",
    notes:
      "Former loaner unit with low miles, full factory warranty remaining. Payment is +tax. $499 broker fee is included in the due-at-signing total above.",
    packages: [],
    images: ["https://file.kelleybluebookimages.com/kbb/base/evox/CP/55153/2025-Porsche-Macan-front_55153_032_2400x1800_A1.png"],
    sourceUrl:
      "https://forum.leasehackr.com/t/chrome-stallions-benz-porsche-exotics-glb-179-3-5k-glc-279-3-5k-911-4s-1499-5k/759811",
  },

  // ---------------------------------------------------------------------
  // More real Chrome Stallions inventory — sourced from their BMW/Audi,
  // Mercedes/Porsche, and Exotics/Porsche/Land Rover threads (July 2026).
  // Broker fee is included in the due-at-signing total shown for each deal.
  // ---------------------------------------------------------------------
  {
    id: 21,
    slug: "2026-bmw-x5-xdrive40i-msport-skyscraper-gray-ca",
    year: 2026,
    make: "BMW",
    model: "X5",
    trim: "xDrive40i M Sport",
    bodyStyle: "SUV",
    fuel: "Gas",
    exterior: "Skyscraper Gray",
    interior: "Black",
    dealType: "Lease",
    msrp: 84000, // estimated — Chrome Stallions posts selling price, not full MSRP; confirm sticker with broker
    sellingPrice: 78000,
    payment: 819,
    dueAtSigning: 3500,
    term: 39,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "Chrome Stallions",
    sellerPhone: "949-763-5609",
    sellerEmail: "sales@chromestallions.com",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 68,
    datePosted: "2026-05-06",
    badge: "HOT",
    notes:
      "Payment is +tax. BMW deals require loyalty — a BMW currently registered in the household. $599 broker fee is included in the due-at-signing total above.",
    packages: ["M Sport", "Parking Assistance", "21\" Wheels", "Trailer Hitch", "4-Zone Climate"],
    images: ["https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/o10qiMPxXkopc2mFsQ0AUs_xru79YZFSeXSVQkY2w4NlDrU74XvajDCTMdJdgADwu8ZxJ1V9jM9BMEarQAyVaolWMasMH1Tzf663PxdnfXkHzPXTfExsO0L3cz2eHhZCh3OfTtNXhqEzmBB7WGGJnohwhCnijuOjpR0qHuJvKIL7dogXDH0VYw5ojcjGgr7Uwsybs5-BLNw/cc_2026BMS191998062_01_640_C36.png"],
    sourceUrl:
      "https://forum.leasehackr.com/t/chrome-stallions-bmw-audi-i4-415-3-5k-x5e-829-3-5k-740-885-3-5k-q7-699-3-5k/759812",
  },
  {
    id: 22,
    slug: "2026-bmw-i4-edrive40-black-real-ca",
    year: 2026,
    make: "BMW",
    model: "i4 eDrive40",
    trim: "Premium",
    bodyStyle: "Sedan",
    fuel: "EV",
    exterior: "Black",
    interior: "Black",
    dealType: "Lease",
    msrp: 66000,
    sellingPrice: 62000,
    payment: 435,
    dueAtSigning: 3500,
    term: 36,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "Chrome Stallions",
    sellerPhone: "949-763-5609",
    sellerEmail: "sales@chromestallions.com",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 61,
    datePosted: "2026-05-06",
    badge: "EV",
    notes:
      "Payment is +tax. BMW deals require loyalty — a BMW currently registered in the household. $599 broker fee is included in the due-at-signing total above.",
    packages: ["Premium Package", "Driving Assistance"],
    images: ["https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/o10qiMPxXkpewSF6eUJXr3lvFYdV-b4Is-XetRvtnAvIQGH-ZKq4PLJ2wjzesxpGlwXWIK56HSkiULTwl4u5LW-yXuLVeG2qURtorTZdK0uVoFWeriC8LQogCQacqNpEcwQnEe9KurMgyWT-1reon5Kc0ECzBS8ibtonSH-AnKQwiZWvo0Jndg/cc_2026BMCA12021366_01_640_475.png"],
    sourceUrl:
      "https://forum.leasehackr.com/t/chrome-stallions-bmw-audi-i4-415-3-5k-x5e-829-3-5k-740-885-3-5k-q7-699-3-5k/759812",
  },
  {
    id: 23,
    slug: "2026-bmw-740i-brooklyn-gray-ca",
    year: 2026,
    make: "BMW",
    model: "740i",
    trim: "xDrive M-Sport Professional",
    bodyStyle: "Sedan",
    fuel: "Gas",
    exterior: "Brooklyn Gray",
    interior: "Mocha",
    dealType: "Lease",
    msrp: 112000,
    sellingPrice: 105000,
    payment: 899,
    dueAtSigning: 3500,
    term: 39,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "Chrome Stallions",
    sellerPhone: "949-763-5609",
    sellerEmail: "sales@chromestallions.com",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 54,
    datePosted: "2026-05-06",
    badge: "NEW",
    notes:
      "Payment is +tax. BMW deals require loyalty — a BMW currently registered in the household. $699 broker fee is included in the due-at-signing total above.",
    packages: ["Driving Assistance Pro", "Premium", "M-Sport Professional", "Alcantara Headliner"],
    images: ["https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/o10qiMPxXkqC4sTjZ1QIbMkqejuDBEg8x37QMnp4nmnDlruDNFrRqpuUSEIFtOcUQqnRZud1t6wHsoBQhZOt5KFWVGm2uawx8k_lOmwTSmBcaLXil7qk7BnvGhTBe_HDnQb2Juewvm3q0_Nqn7bdeGO9tgru7mF4-xXfAvTzoj9zD08ulFXjQg/cc_2026BMC082046588_01_640_C4P.png"],
    sourceUrl:
      "https://forum.leasehackr.com/t/chrome-stallions-bmw-audi-i4-415-3-5k-x5e-829-3-5k-740-885-3-5k-q7-699-3-5k/759812",
  },
  {
    id: 24,
    slug: "2026-bmw-x3-30-white-ca",
    year: 2026,
    make: "BMW",
    model: "X3",
    trim: "30 xDrive",
    bodyStyle: "SUV",
    fuel: "Gas",
    exterior: "White",
    interior: "Beige",
    dealType: "Lease",
    msrp: 59000,
    sellingPrice: 55000,
    payment: 509,
    dueAtSigning: 3500,
    term: 39,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "Chrome Stallions",
    sellerPhone: "949-763-5609",
    sellerEmail: "sales@chromestallions.com",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 57,
    datePosted: "2026-05-06",
    badge: "VALUE",
    notes:
      "Payment is +tax. BMW deals require loyalty — a BMW currently registered in the household. $599 broker fee is included in the due-at-signing total above.",
    packages: ["Convenience Package", "Glow Grill"],
    images: ["https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/o10qiMPxXkoxFD7oJYIQxSKyjANEuKNyF29qOCq7Xsilj5Zke2lneSpOOg8cn9piDEPhQ1gjdgea7BVjXgjVgMtgmD30xD-L06mzfCqo5ya-cQi6wcvpFgY4Z7M7LGJF774Y40pmNGdgOdg1TOWZsqS6lWYsj-VXEsKcoaCOSCse0OTpKlmnbRgZFIOKKlQybvtt_jzYFMQQlKenPLNITQ/cc_2026BMS202001149_01_640_300.png"],
    sourceUrl:
      "https://forum.leasehackr.com/t/chrome-stallions-bmw-audi-i4-415-3-5k-x5e-829-3-5k-740-885-3-5k-q7-699-3-5k/759812",
  },
  {
    id: 25,
    slug: "2025-audi-a5-premium-plus-loaner-ca",
    year: 2025,
    make: "Audi",
    model: "A5",
    trim: "Premium Plus",
    bodyStyle: "Sedan",
    fuel: "Gas",
    exterior: "Mythos Black",
    interior: "Black",
    dealType: "Lease",
    msrp: 54000,
    sellingPrice: 49000,
    payment: 319,
    dueAtSigning: 3000,
    term: 36,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "Chrome Stallions",
    sellerPhone: "949-763-5609",
    sellerEmail: "sales@chromestallions.com",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 50,
    datePosted: "2026-05-06",
    badge: "VALUE",
    notes:
      "Loaner unit with low miles. Payment is +tax. Audi loyalty incentive may apply — ask broker for current eligibility. $699 broker fee is included in the due-at-signing total above.",
    packages: ["Warm Weather Package", "19\" Wheel Package"],
    images: ["https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/yWhhamuIqoYVO2hbFBmRgVaCtskpU2OI-PGYbRSaYLFJWt2bWvCG-_v-oOdJGkurVSV4d9cHrmckwxAdmynBUMZzvFJomlG2EoWBIRl9Orkk3B4-265hLstgkUSqevWpo1R3LiKdZmbLmPPYQID5KYmGBH1LX_Mv0eHC2s0eMzawYOp7nwG8ohTVFzFLXncM/cc_2025AUC432047398_01_640_0E0E.png"],
    sourceUrl:
      "https://forum.leasehackr.com/t/chrome-stallions-bmw-audi-i4-415-3-5k-x5e-829-3-5k-740-885-3-5k-q7-699-3-5k/759812",
  },
  {
    id: 26,
    slug: "2025-audi-s5-premium-plus-ca",
    year: 2025,
    make: "Audi",
    model: "S5",
    trim: "Premium Plus",
    bodyStyle: "Sedan",
    fuel: "Gas",
    exterior: "Black",
    interior: "Black",
    dealType: "Lease",
    msrp: 67000,
    sellingPrice: 63000,
    payment: 699,
    dueAtSigning: 3500,
    term: 36,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "Chrome Stallions",
    sellerPhone: "949-763-5609",
    sellerEmail: "sales@chromestallions.com",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 46,
    datePosted: "2026-05-06",
    badge: "NEW",
    notes:
      "Payment is +tax. Audi loyalty incentive may apply — ask broker for current eligibility. $599 broker fee is included in the due-at-signing total above.",
    packages: ["Sports Seats Plus", "Sport Adaptive Damping Suspension"],
    images: ["https://autoimage.capitalone.com/stock-media/chrome/2025-Audi-S5-Premium_Plus-0E0E-cc_2025AUC441987508_01_2100_0E0E.png"],
    sourceUrl:
      "https://forum.leasehackr.com/t/chrome-stallions-bmw-audi-i4-415-3-5k-x5e-829-3-5k-740-885-3-5k-q7-699-3-5k/759812",
  },
  {
    id: 27,
    slug: "2026-mercedes-benz-gls-450-white-ca",
    year: 2026,
    make: "Mercedes-Benz",
    model: "GLS 450",
    trim: "Base",
    bodyStyle: "SUV",
    fuel: "Gas",
    exterior: "Polar White",
    interior: "Black",
    dealType: "Lease",
    msrp: 99000,
    sellingPrice: 93000,
    payment: 899,
    dueAtSigning: 3500,
    term: 36,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "Chrome Stallions",
    sellerPhone: "949-763-5609",
    sellerEmail: "sales@chromestallions.com",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 59,
    datePosted: "2026-05-06",
    badge: "NEW",
    notes:
      "7-seater. Payment is +tax. Requires Conquest — an eligible 2020+ vehicle currently registered to you or someone in your household. $699 broker fee is included in the due-at-signing total above.",
    packages: ["7-Seater", "Running Boards"],
    images: ["https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/A6ZVqgdvNgOXXRFeSA7pCkZUeruSm8O3Jo2-SqimNwWgcLZQmer8E9O3RCE7dJyYLRpsGp3b_QqnZga4gStJsK5g1UZoPY4y12M87lYgFM1Dyn5-nSLUcd_dGzzsmvKkQ-48RWilI_UmCyBNTMUgDQuJH3-D521OFUJFNwMCHcfduxlv-U6i7ZM1zGpYNhwi/cc_2026MBS631971493_01_640_040.png"],
    sourceUrl:
      "https://forum.leasehackr.com/t/chrome-stallions-benz-porsche-exotics-glb-179-3-5k-glc-279-3-5k-911-4s-1499-5k/759811",
  },
  {
    id: 28,
    slug: "2026-mercedes-benz-cle53-amg-coupe-blue-ca",
    year: 2026,
    make: "Mercedes-Benz",
    model: "CLE 53 AMG Coupe",
    trim: "4MATIC",
    bodyStyle: "Coupe",
    fuel: "Gas",
    exterior: "Starling Blue",
    interior: "Black",
    dealType: "Lease",
    msrp: 91000,
    sellingPrice: 86000,
    payment: 859,
    dueAtSigning: 3500,
    term: 24,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "Chrome Stallions",
    sellerPhone: "949-763-5609",
    sellerEmail: "sales@chromestallions.com",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 63,
    datePosted: "2026-05-06",
    badge: "HOT",
    notes:
      "Payment is +tax. Requires Conquest — an eligible 2020+ vehicle currently registered to you or someone in your household. $699 broker fee is included in the due-at-signing total above.",
    packages: ["Pinnacle Trim", "AMG Carbon Fiber", "20\" AMG Y-Design Wheels"],
    images: ["https://pub-2581946c35634f46958be8b522976200.r2.dev/2026-Mercedes-Benz-CLE-AMG-CLE-53-4MATIC+-Coupe-PSRQ-Starling-Blue-Metallic-970.webp"],
    sourceUrl:
      "https://forum.leasehackr.com/t/chrome-stallions-benz-porsche-exotics-glb-179-3-5k-glc-279-3-5k-911-4s-1499-5k/759811",
  },
  {
    id: 29,
    slug: "2026-porsche-cayenne-black-ca",
    year: 2026,
    make: "Porsche",
    model: "Cayenne",
    trim: "Base",
    bodyStyle: "SUV",
    fuel: "Gas",
    exterior: "Black",
    interior: "Black",
    dealType: "Lease",
    msrp: 104000,
    sellingPrice: 98000,
    payment: 1179,
    dueAtSigning: 3500,
    term: 39,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "Chrome Stallions",
    sellerPhone: "949-763-5609",
    sellerEmail: "sales@chromestallions.com",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 56,
    datePosted: "2026-07-03",
    badge: "NEW",
    notes:
      "Payment is +tax. $699 broker fee is included in the due-at-signing total above.",
    packages: ["21\" RS Spyder Design Wheels", "Bose Surround Sound"],
    images: ["https://vehicle-images.carscommerce.inc/stock-images/chrome/a0d9861200321d9920b42359c78f8bfc.png"],
    sourceUrl:
      "https://forum.leasehackr.com/t/chrome-stallions-exotics-porsche-benteyga-1675-10k-911-4s-1499-5k-urus-se-onepay-54-999/770167",
  },
  {
    id: 30,
    slug: "2026-porsche-panamera-ca",
    year: 2026,
    make: "Porsche",
    model: "Panamera",
    trim: "Base",
    bodyStyle: "Sedan",
    fuel: "Gas",
    exterior: "Provence",
    interior: "Black",
    dealType: "Lease",
    msrp: 130000,
    sellingPrice: 122000,
    payment: 1599,
    dueAtSigning: 4000,
    term: 39,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "Chrome Stallions",
    sellerPhone: "949-763-5609",
    sellerEmail: "sales@chromestallions.com",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 52,
    datePosted: "2026-07-03",
    badge: "NEW",
    notes:
      "Payment is +tax. $699 broker fee is included in the due-at-signing total above.",
    packages: [],
    images: ["https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/OO0oYT4gvcinee8qh7E42h-JRo4qfmVAaV4u0bRIt5H9NdFIRA_JHTqOW6nLSUwdAosD5_nMkAYeLxNVEhd8LxLiR5k7hZqmle9E6kBQtEX3E6ZoDBlJeoah8LUTmAo_8ldIiEqqfSMmgvPf2eHXNzmJ2SQU-XlKMIJoKggQ338/cc_2026PRC101979607_01_640_A1.png"],
    sourceUrl:
      "https://forum.leasehackr.com/t/chrome-stallions-exotics-porsche-benteyga-1675-10k-911-4s-1499-5k-urus-se-onepay-54-999/770167",
  },
  {
    id: 31,
    slug: "2026-land-rover-range-rover-evoque-blue-ca",
    year: 2026,
    make: "Land Rover",
    model: "Range Rover Evoque",
    trim: "Core S AWD",
    bodyStyle: "SUV",
    fuel: "Gas",
    exterior: "Tribeca Blue Metallic",
    interior: "Ebony",
    dealType: "Lease",
    msrp: 57000,
    sellingPrice: 53000,
    payment: 629,
    dueAtSigning: 4000,
    term: 36,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "Chrome Stallions",
    sellerPhone: "949-763-5609",
    sellerEmail: "sales@chromestallions.com",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 45,
    datePosted: "2026-07-03",
    badge: "VALUE",
    notes:
      "Payment is +tax. Requires a qualifying conquest incentive — confirm current eligibility with broker. $599 broker fee is included in the due-at-signing total above.",
    packages: [],
    images: ["https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/5MUaBu0KmqADayDAt3BDFnHAPcBgxUUaIsCkkCrbiTHFtfZP1Er8jO2H1GyaMIWI-SbVlyzquVsh8krJ4Ocxmg9ikphqTy_brq6gxmRfjOwVWlri4pIiaw8GCWj5KTT42AOBQgFPkCxOlFlXCvN0bkI4uzdWgrF4lAbTQPO3wfY/cc_2026LRS101942839_01_640_1FV.png"],
    sourceUrl:
      "https://forum.leasehackr.com/t/chrome-stallions-exotics-porsche-benteyga-1675-10k-911-4s-1499-5k-urus-se-onepay-54-999/770167",
  },
  {
    id: 32,
    slug: "2026-land-rover-range-rover-velar-p250-ca",
    year: 2026,
    make: "Land Rover",
    model: "Range Rover Velar",
    trim: "P250 S",
    bodyStyle: "SUV",
    fuel: "Gas",
    exterior: "Santorini Black Metallic",
    interior: "Ebony",
    dealType: "Lease",
    msrp: 71000,
    sellingPrice: 67000,
    payment: 714,
    dueAtSigning: 4000,
    term: 36,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "Chrome Stallions",
    sellerPhone: "949-763-5609",
    sellerEmail: "sales@chromestallions.com",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 43,
    datePosted: "2026-07-03",
    badge: "NEW",
    notes:
      "Payment is +tax. Requires a qualifying conquest incentive — confirm current eligibility with broker. $599 broker fee is included in the due-at-signing total above.",
    packages: [],
    images: ["https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/5MUaBu0KmqAD5cudKFDps7olY_R1WkPc0y1uUTvcJvN6lmeRdckDtxH8BlKBDTAa90wFRLknVcB18lBFIeuciuPLA9FHIn9gyfXOL5mDUfSaxIm-8fG0C-srxUfwE7iAfq0tBDiGWxTkexd14FoiYA4CEWBC89S8WY3UTJ5WGfF1GLvEy1BL3g/cc_2026LRS122044623_01_640_1EH.png"],
    sourceUrl:
      "https://forum.leasehackr.com/t/chrome-stallions-exotics-porsche-benteyga-1675-10k-911-4s-1499-5k-urus-se-onepay-54-999/770167",
  },
  {
    id: 33,
    slug: "2026-land-rover-defender-110-gray-ca",
    year: 2026,
    make: "Land Rover",
    model: "Defender 110",
    trim: "P400 X-Dynamic SE",
    bodyStyle: "SUV",
    fuel: "Gas",
    exterior: "Borasco Grey Metallic",
    interior: "Ebony",
    dealType: "Lease",
    msrp: 94000,
    sellingPrice: 88000,
    payment: 1069,
    dueAtSigning: 4000,
    term: 36,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "Chrome Stallions",
    sellerPhone: "949-763-5609",
    sellerEmail: "sales@chromestallions.com",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 60,
    datePosted: "2026-07-03",
    badge: "HOT",
    notes:
      "Interior trim not specified by broker; shown as manufacturer-standard Ebony — confirm exact spec before signing. Also available in Black, Dark Grey, and Light Grey. Payment is +tax. Requires a qualifying conquest incentive — confirm current eligibility with broker. $599 broker fee is included in the due-at-signing total above.",
    packages: [],
    images: ["https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/5MUaBu0KmqAT6MZYXbuUmh24enC1a7JKB8ftzqK6q6xsG3rHct4EW6fSeGp_9mVCjSkzAUUenQXk4zxXjPEitFbtRn4vhZ7O7ChfsmxBUXmVryYbUgaEH-XhfvfRwc0AM3yb4RzrbSKgv14dJhD2lgG7yptJYd9Zmuq3arTr_Fk/cc_2026LRS132046010_01_640_1CN.png"],
    sourceUrl:
      "https://forum.leasehackr.com/t/chrome-stallions-exotics-porsche-benteyga-1675-10k-911-4s-1499-5k-urus-se-onepay-54-999/770167",
  },
  {
    id: 34,
    slug: "2023-bentley-bentayga-ewb-v8-ca",
    year: 2023,
    make: "Bentley",
    model: "Bentayga EWB",
    trim: "V8",
    bodyStyle: "SUV",
    fuel: "Gas",
    exterior: "Onyx",
    interior: "Linen",
    dealType: "Lease",
    msrp: 285000, // estimated — CPO/pre-owned unit, see note below
    sellingPrice: 260000,
    payment: 1675,
    dueAtSigning: 10000,
    term: 24,
    milesPerYear: 7500,
    apr: null,
    sellerType: "Broker",
    sellerName: "Chrome Stallions",
    sellerPhone: "949-763-5609",
    sellerEmail: "sales@chromestallions.com",
    city: "Los Angeles",
    state: "CA",
    verified: true,
    inStock: true,
    popularity: 71,
    datePosted: "2026-07-07",
    badge: "HOT",
    notes:
      "Extended wheelbase V8. Payment is +tax. $1,299 broker fee is included in the due-at-signing total above.",
    packages: [],
    images: ["https://static.tcimg.net/vehicles/primary/f3f14dd92d0777c7/2023-Bentley-Bentayga-gray-full_color-driver_side_profile.png"],
    sourceUrl:
      "https://forum.leasehackr.com/t/chrome-stallions-exotics-porsche-benteyga-1675-10k-911-4s-1499-5k-urus-se-onepay-54-999/770167",
  },
];

// -----------------------------------------------------------------------------
// Derived filter option lists (auto-generated from the data above)
// -----------------------------------------------------------------------------
export const MAKES = ["All", ...Array.from(new Set(deals.map((d) => d.make))).sort()];
export const SELLERS = ["All", ...Array.from(new Set(deals.map((d) => d.sellerName))).sort()];
export const BODY_STYLES: BodyStyle[] = [
  "Sedan",
  "SUV",
  "Truck",
  "Coupe",
  "Minivan",
  "Hatchback",
];
export const STATES = ["All", ...Array.from(new Set(deals.map((d) => d.state))).sort()];
export const FUEL_TYPES: FuelType[] = ["Gas", "Hybrid", "PHEV", "EV"];
export const TERMS = ["All", ...Array.from(new Set(deals.map((d) => String(d.term)))).sort(
  (a, b) => Number(a) - Number(b)
)];
export const MILEAGE_OPTIONS = [
  "All",
  ...Array.from(
    new Set(deals.filter((d) => d.milesPerYear != null).map((d) => String(d.milesPerYear)))
  ).sort((a, b) => Number(a) - Number(b)),
];

export function getDealBySlug(slug: string): Deal | undefined {
  return deals.find((d) => d.slug === slug);
}

export function getSimilarDeals(deal: Deal, count = 3): Deal[] {
  return deals
    .filter((d) => d.id !== deal.id)
    .map((d) => {
      let score = 0;
      if (d.make === deal.make) score += 2;
      if (d.bodyStyle === deal.bodyStyle) score += 2;
      if (d.fuel === deal.fuel) score += 1;
      if (d.state === deal.state) score += 1;
      return { deal: d, score };
    })
    .sort((a, b) => b.score - a.score)
    .slice(0, count)
    .map((entry) => entry.deal);
}
